### ISSUE TITLE
Update a cluster Mysql RDS on Flexible Engine

### ISSUE THREAD

**Issue by yeplaa** [huaweicloud/huaweicloud-service-broker#66]
Hello,

From Openshift Origin, i use huaweicloud-service-broker for provision RDS Mysql 5.7.21 on Flexible Engine OBS. The provisioning works.
After, I would like to test an update of the service instance as indicated on the doc.

Bellow my config used for the provisionning of Primary/Standby Mysql Cluster : 

    apiVersion: servicecatalog.k8s.io/v1beta1
    kind: ServiceInstance
    metadata:
      name: mysqlha1
      namespace:  dbms
    spec:
    # References service name and plan name
    clusterServiceClassExternalName: rds-mysql
    clusterServicePlanExternalName: 5.7.21
    # Additional parameters can be added here,
    # which may be used by the service broker.
    parameters:
      name: "mysqlha1"
      database_password: "Password1234!"
      speccode: "rds.mysql.s1.xlarge.ha"
      ha_enable: true
      volume_type: "ULTRAHIGH"
      ha_replicationmode: "async"

After the cluster is up, below my configuration for the update of Serviceinstance :

     apiVersion: servicecatalog.k8s.io/v1beta1
     kind: ServiceInstance
     metadata:
       name: mysqlha1
       namespace:  dbms
     spec:
       # References service name and plan name
       clusterServiceClassExternalName: rds-mysql
       clusterServicePlanExternalName: 5.7.21
       # Additional parameters can be added here,
       # which may be used by the service broker.
       parameters:
         name: "mysqlha1"
         speccode: "rds.mysql.s1.large.ha"
         volume_size: "150"

As indicated, i would update the **speccode**  and the **volume_size**.
I use *oc apply* for update this serviceInstance.

Bellow the errors of servvice-broker pod  : 
          {"timestamp":"1544447759.164404631","source":"ServiceBroker","message":"ServiceBroker.unknown-error","log_level":2,"data":{"error":"planid is empty"}}

Also, i tried to add this configuration on my update.yaml file but no change : 

      # References service instance name
      instanceRef:
        name: mysqlha1

What is the syntax I need to use for the update?

Thank's
Loïc

**Comment by edisonxiang** [comment]
Hi @yeplaa Thanks your issue.
Actually it is a bug for update serviceInstance.
I will submit a pr to solve this bug and rebuild the docker image for this respositorty.
Thanks.

**Comment by edisonxiang** [comment]
Hi @yeplaa, this issue about "the planid is empty" is fixed.
but we have two update APIs, one is for "speccode", another one is for "volume_size".
https://docs.prod-cloud-ocb.orange-business.com/en-us/api/rds/en-us_topic_0037365603.html https://docs.prod-cloud-ocb.orange-business.com/en-us/api/rds/en-us_topic_0034943367.html
Currently we can only update one of the parameters "speccode" and "volume_size" at a time or one by one.

For example, you can run the following yaml to **create** the instance.
```
......
parameters:
  name: "mysqlha1"
  database_password: "Password1234!"
  speccode: "rds.mysql.s1.xlarge.ha"
  ha_enable: true
  volume_type: "ULTRAHIGH"
  ha_replicationmode: "async"
```
and then run the following yaml to **update** the instance "speccode".
```
......
parameters:
  name: "mysqlha1"
  database_password: "Password1234!"
  speccode: "rds.mysql.s1.2xlarge.ha"
  ha_enable: true
  volume_type: "ULTRAHIGH"
  ha_replicationmode: "async"
```
at last run the following yaml to **update** the instance "volume_size".
```
......
parameters:
  name: "mysqlha1"
  database_password: "Password1234!"
  speccode: "rds.mysql.s1.2xlarge.ha"
  ha_enable: true
  volume_type: "ULTRAHIGH"
  ha_replicationmode: "async"
  volume_size: "150"
```
I will find some ways to support updating these two parameters "speccode" and "volume_size" at the same time later. 

Thanks your issue.
